MobileTeleSystems/syncmaster

.readthedocs.yaml
README.rst
docs/_static/custom.css
docs/_static/openapi.json
docs/_static/redoc.html
docs/_static/swagger.html
docs/design/permissions.rst
docs/index.rst
poetry.lock
pyproject.toml

https://syncmaster.readthedocs.io/en/latest/

[DOP-11710] Move documentation to ReadTheDocs

---

docs/changelog/next_release/40.bugfix.rst
syncmaster/backend/api/v1/connections.py
syncmaster/backend/api/v1/transfers.py
syncmaster/db/repositories/credentials_repository.py

Using `asyncio.gather` with SQLAlchemy may result some unexpected errors: https://github.com/sqlalchemy/sqlalchemy/discussions/9312. We should avoid using it.
Also even `asyncio.gather` is still expensive because each `for loop` iteration sends a separated query to the database. Replaced it with `connection_id IN (...)` clause, reducing to just one database request.

[DOP-14025] Remove asyncio.gather from SQLAlchemy requests

---

docs/changelog/next_release/39.bugfix.rst
syncmaster/backend/api/v1/connections.py
syncmaster/db/repositories/connection.py
syncmaster/db/repositories/credentials_repository.py
syncmaster/db/repositories/utils.py
tests/test_unit/test_connections/test_update_connection.py

Fixed bug when sending `PATCH v1/connections/:id` request with new `auth_data.password` value returned 500 error with traceback:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
result = await app(  # type: ignore[func-returns-value]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
return await self.app(scope, receive, send)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
await super().__call__(scope, receive, send)
File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__ …
```

[DOP-14025] Fix patching connection with new auth_data.password value

---

.github/workflows/cache-cleanup.yml
.github/workflows/codeql-analysis.yml
.github/workflows/hdfs-tests.yml
.github/workflows/hive-tests.yml
.github/workflows/oracle-tests.yml
.github/workflows/release.yaml
.github/workflows/s3-tests.yml
.github/workflows/unit-test.yml

Github has a limit for CI cache - 10Gb per repo. Active images caching leads to cache size exceeding the limit, and thus cache items are evicted. Including caches from develop branch which are used as a seed for caches in other branches.
Here I've added CI workflow which deletes caches related to feature/bugfix branch, just after PR is merged/closed.

[DOP-14025] Add workflow for cleanup CI cache

---

.github/workflows/hdfs-tests.yml
.github/workflows/hive-tests.yml
.github/workflows/oracle-tests.yml
.github/workflows/s3-tests.yml
docs/changelog/next_release/46.bugfix.rst
syncmaster/worker/spark.py
tests/test_integration/test_run_transfer/conftest.py

* Use only Spark packages required by selected tests, e.g. download Oracle package only if Oracle tests are running. This reduces both .jar cache size (500Mb -> 1.5Mb) and Spark session startup time.
* Use hadoop-aws `magic` commiter only if S3 is a *target*. Previously it was used only if S3 is a *source*, but this does not make any sense, commiter is used only for writing data.

[DOP-15512] Download only packages required by tests

---

docs/changelog/next_release/63.bugfix.rst
syncmaster/backend/api/v1/transfers.py
syncmaster/db/repositories/run.py
syncmaster/schemas/v1/connections/connection.py
tests/test_integration/test_run_transfer/test_hdfs.py
tests/test_integration/test_run_transfer/test_hve.py
tests/test_integration/test_run_transfer/test_oracle.py
tests/test_integration/test_run_transfer/test_s3.py

[DOP-17107] dump connection auth data

---

syncmaster/backend/__init__.py
syncmaster/backend/api/deps.py
syncmaster/backend/services/__init__.py
syncmaster/backend/services/auth.py
syncmaster/config.py
syncmaster/db/repositories/group.py

When Group had a lot of bound UserGroup rows, the page limit in `GET /v1/groups` was applied to these rows instead of distinct Groups. Fixed.
Also fix missing "Authorize" button in Swagger.

[DOP-19835] Fix GET /v1/groups skipping some groups

---

syncmaster/backend/api/v1/users.py
tests/test_unit/test_users.py

In the endpoint for managing group permissions, a user identifier was required. Previously, it could only be obtained by iterating through all users and comparing the login with the current one. Instead, a new endpoint GET /users/me has been added, which returns the details of the current user.

[DOP-19780] Add /users/me endpoint

---

docs/changelog/next_release/97.breaking.rst
syncmaster/backend/api/v1/groups.py
syncmaster/db/models.py
syncmaster/db/repositories/group.py
syncmaster/schemas/v1/groups.py
tests/mocks.py
tests/test_unit/conftest.py
tests/test_unit/test_groups/test_add_user_to_group.py
tests/test_unit/test_groups/test_read_groups.py
tests/test_unit/test_groups/test_update_member_role.py

- change response format for endpoint `GET /v1/groups` from:
```
{
"meta": {
"page": 1,
"pages": 1,
"total": 2,
"page_size": 20,
"has_next": False,
"has_previous": False,
"next_page": None,
"previous_page": None,
},
"items": [
{
"id": 18698,
"name": "group_for_Maintainer",
"description": "",
"owner_id": 73055,
},
{
"id": 18699,
"name": "group_for_Developer",
"description": "",
"owner_id": 73055,
},
]
}
```
to: 
```
{
"meta": {
"page": 1,
"pages": 1,
"total": 2,
"page_size": 20,
"has_next": False,
"has_previous": False,
"next_page": None,
"previous_page": None,
},
"items": [
{
"data": {
"id": 18698,
"name": "group_for_Maintainer",
"description": "",
"owner_id": 73055,
},
"role": "Maintainer",
},
{
"data": {
"id": 18700,
"name": "group_for_Guest",
"description": "",
"owner_id": 73055,
}, …
```

[DOP-19935] - add <role> attribute to /v1/groups response

---

docs/changelog/next_release/109.breaking.rst
syncmaster/backend/api/v1/groups.py
syncmaster/db/repositories/group.py
tests/test_unit/test_groups/test_read_group_by_id.py
tests/test_unit/test_groups/test_update_group_by_id.py

GET /v1/groups/:id endpoint changed the response format from:
```
{
“id": 123,
“name": "abc",
“description": “cde”
}
```
to
```
{
“data": {
“id": 123,
“name": "abc",
“description": “cde”
}, 
“role”: “DEVELOPER”
}
```

[DOP-20893] Add <role> attribute to /v1/groups/:id response

---

.env.docker
.env.local
docs/backend/configuration/logging.rst
poetry.lock
pyproject.toml
syncmaster/backend/api/v1/runs.py
syncmaster/settings/__init__.py
syncmaster/settings/log/__init__.py
syncmaster/settings/log/colored.yml
syncmaster/settings/log/json.yml
syncmaster/settings/log/plain.yml
syncmaster/settings/server/__init__.py
syncmaster/settings/worker/__init__.py
syncmaster/worker/transfer.py
tests/test_unit/test_runs/test_create_run.py

- Add logic for updating `log_url` in `Run` table rendered from template for future viewing of celery worker logs
- Add `WorkerSettings` to configure work of celery worker (logging, log_url_template, etc.)

[DOP-19796] - add log_url before sending run task to celery worker

---

syncmaster/backend/api/v1/runs.py
tests/test_unit/test_runs/test_create_run.py
tests/test_unit/test_scheduler/test_transfer_job_manager.py

The call to the synchronous celery.send_task() method in the asynchronous endpoint is wrapped in asyncio.to_thread to avoid event loop blocking, in particular when RabbitMQ is unavailable.

[DOP-19794] Do not block event loop when using Celery

---

docker-compose.test.yml
docs/changelog/next_release/119.bugfix.rst
syncmaster/db/migrations/versions/2023-11-23_0003_create_queue_table.py
syncmaster/db/models/group.py
syncmaster/db/models/queue.py
syncmaster/db/repositories/queue.py
syncmaster/schemas/v1/queue.py
tests/test_unit/conftest.py
tests/test_unit/test_queue/test_create_queue.py
tests/test_unit/test_queue/test_read_queue.py
tests/test_unit/test_queue/test_read_queues.py
tests/test_unit/test_queue/test_update_queue.py
tests/test_unit/utils.py

Previously, the `Queue` `name` field was unique among all groups. Now it is made unique within `group_id`. For this purpose, an additional read-only field `slug` is added, which is generated as `$group_id-$name`. We use this field as the name of the queue in RabbitMQ.

[DOP-19793] Make queue name unique within a group

---

docker-compose.yml
docs/backend/configuration/index.rst
docs/backend/configuration/monitoring.rst
docs/changelog/next_release/121.feature.rst
poetry.lock
pyproject.toml
syncmaster/backend/api/monitoring.py
syncmaster/backend/middlewares/__init__.py
syncmaster/backend/middlewares/monitoring/__init__.py
syncmaster/backend/middlewares/monitoring/metrics.py
syncmaster/backend/utils/__init__.py
syncmaster/backend/utils/slug.py
syncmaster/schemas/__init__.py
syncmaster/schemas/ping.py
syncmaster/settings/server/__init__.py
syncmaster/settings/server/monitoring.py

Added a new monitoring endpoint at `GET /v1/monitoring/metrics`, along with the necessary configuration and middleware. Updated the documentation to include a section on monitoring setup and usage.

[DOP-19925] Add GET v1/monitoring/metrics endpoint

---

README.rst
docs/changelog/next_release/125.feature.rst
syncmaster/backend/api/v1/connections.py
syncmaster/schemas/v1/connection_types.py
syncmaster/schemas/v1/connections/connection.py
syncmaster/schemas/v1/connections/mssql.py
syncmaster/schemas/v1/transfers/__init__.py
syncmaster/schemas/v1/transfers/db.py
tests/test_unit/test_connections/connection_fixtures/group_connections_fixture.py
tests/test_unit/test_connections/test_create_connection.py
tests/test_unit/test_connections/test_db_connection/test_create_mssql_connection.py
tests/test_unit/test_connections/test_db_connection/test_update_mssql_connection.py
tests/test_unit/test_connections/test_read_connections.py
tests/test_unit/test_transfers/test_create_transfer.py
tests/test_unit/test_transfers/transfer_fixtures/transfers_fixture.py

- Added Pydantic schemas for MSSQL connection
- Added Pydantic schemas for MSSQL source parameters and target parameters
- Added unit tests for creating & updating MSSQL connection and target
- Updated README to include references to MSSQL 

[DOP-19900] Add MSSQL API schema

---

README.rst
docs/changelog/next_release/126.feature.rst
syncmaster/backend/api/v1/connections.py
syncmaster/schemas/v1/connection_types.py
syncmaster/schemas/v1/connections/connection.py
syncmaster/schemas/v1/connections/mysql.py
syncmaster/schemas/v1/transfers/__init__.py
syncmaster/schemas/v1/transfers/db.py
tests/test_unit/test_connections/connection_fixtures/group_connections_fixture.py
tests/test_unit/test_connections/test_create_connection.py
tests/test_unit/test_connections/test_db_connection/test_create_mysql_connection.py
tests/test_unit/test_connections/test_db_connection/test_update_mysql_connection.py
tests/test_unit/test_connections/test_read_connections.py
tests/test_unit/test_transfers/test_create_transfer.py
tests/test_unit/test_transfers/transfer_fixtures/transfers_fixture.py

- Added Pydantic schemas for MySQL connection
- Added Pydantic schemas for MySQL source parameters and target parameters
- Added unit tests for creating & updating MySQL connection and target
- Updated README to include references to MySQL

[DOP-19902] Add MySQL API schema

---

docker-compose.test.yml

The [commit](https://github.com/MobileTeleSystems/syncmaster/pull/118/commits/8144b460a614fb87c173f2df9014426e56bb5a66) in [PR #118](https://github.com/MobileTeleSystems/syncmaster/pull/118) led to a 5% decrease in coverage (in particular, it was about worker module). The initial value has now been restored.

[DOP-21350] Fix test coverage percentage

---

docs/changelog/next_release/135.feature.rst
syncmaster/backend/api/v1/groups.py
syncmaster/backend/handler.py
syncmaster/db/repositories/group.py
syncmaster/exceptions/group.py
tests/test_unit/test_connections/connection_fixtures/group_connections_fixture.py
tests/test_unit/test_groups/test_add_user_to_group.py
tests/test_unit/test_groups/test_update_group_by_id.py

Updated group ownership transfer logic: the previous owner now retains read-only access to the group after transferring ownership. The new owner retains the ability to revoke this access if needed.
Added a restriction to the `POST /groups/{group_id}/users/{user_id}` endpoint to prevent assigning a role to a user who is already a group owner.

[DOP-19926] Grant read-only rights to the previous group owner when ownership is transferred

---

docs/changelog/next_release/160.feature.rst
syncmaster/worker/handlers/db/clickhouse.py
syncmaster/worker/spark.py
tests/test_integration/test_run_transfer/conftest.py
tests/test_integration/test_run_transfer/test_clickhouse.py

Add [spark-dialect-extension](https://github.com/MobileTeleSystems/spark-dialect-extension/) to enhance transfer precision for timestamp columns in `Clickhouse` <-> other supported databases

[DOP-21665] - add spark dialect extension to clickhouse

---

docs/changelog/next_release/161.feature.rst
syncmaster/dto/transfers.py
syncmaster/schemas/v1/transfers/file_format.py
tests/test_integration/test_run_transfer/test_hdfs.py
tests/test_integration/test_run_transfer/test_s3.py
tests/test_unit/test_transfers/test_file_transfers/test_create_transfer.py
tests/test_unit/test_transfers/test_file_transfers/test_read_transfer.py
tests/test_unit/test_transfers/test_file_transfers/test_update_transfer.py

Added a compression parameter to the write settings for XML file format with supported compression values: [XML](https://github.com/databricks/spark-xml?tab=readme-ov-file#features)
Added integration tests to validate compression functionality.

[DOP-21976] Add compression options for XML

---

docker/Dockerfile.worker

- Add  `libkrb5-dev` to `Dockerfile.worker` to use worker in environment with kerberos 

[FEATURE] - add libkrb5-dev to Dockerfile.worker

---

.pre-commit-config.yaml
Makefile
docker-compose.test.yml
docker-compose.yml
docker/Dockerfile.backend
docker/Dockerfile.scheduler
docker/Dockerfile.worker
docker/entrypoint_backend.sh
docs/changelog/next_release/163.breaking.rst
docs/scheduler/start_scheduler.rst
docs/worker/start_worker.rst
poetry.lock
pyproject.toml
syncmaster/backend/providers/auth/dummy_provider.py

* Server, worker & scheduler now depends on standalone container which manages database migrations.
* Server container now has healthcheck
* Replaced `devtools` with `pprint`

[DOP-22054] Move migrations to separated script

---

docker/entrypoint_worker.sh
docs/conf.py
syncmaster/backend/__init__.py
syncmaster/backend/api/v1/runs.py
syncmaster/backend/celery.py
syncmaster/scheduler/__init__.py
syncmaster/scheduler/celery.py
syncmaster/scheduler/transfer_job_manager.py
syncmaster/worker/__init__.py
syncmaster/worker/celery.py
syncmaster/worker/transfer.py
tests/conftest.py
tests/test_integration/celery_test.py
tests/test_integration/test_scheduler/test_scheduler.py
tests/test_integration/test_scheduler/test_task.py
tests/test_unit/test_runs/test_create_run.py
tests/test_unit/test_scheduler/test_transfer_job_manager.py

- Moved Celery instances to separate backend, worker and scheduler modules
- Removed unnecessary variable definitions from `docs/conf.py`

[DOP-21799] Refactor celery initialization

---

syncmaster/backend/api/v1/runs.py
syncmaster/scheduler/transfer_job_manager.py
tests/test_integration/test_run_transfer/conftest.py
tests/test_integration/test_scheduler/scheduler_fixtures/transfer_fixture.py
tests/test_unit/test_runs/test_create_run.py
tests/test_unit/test_scheduler/test_transfer_job_manager.py
tests/test_unit/utils.py

[DOP-22266] - change celery queue name from queue.name to queue.slug

---

docs/changelog/next_release/170.breaking.rst
syncmaster/db/migrations/versions/2023-11-23_0004_create_connection_table.py
syncmaster/db/models/connection.py
syncmaster/db/repositories/connection.py
tests/test_unit/test_connections/test_copy_connection.py
tests/test_unit/test_connections/test_delete_connection.py

- Add deletion of **connections** records instead of marking them as deleted
- Update following tests

[BREAKING] - remove is_deleted for Connection model

---

tests/test_unit/test_auth/auth_fixtures/keycloak_fixture.py

Previously, the auth unit test was flaky in CI due to access token expiration. Its lifetime has now been extended from 1 to 5 seconds. The unit tests were rerun several times and passed successfully.

[DOP-21952] Extend auth token lifetime in the fixture

---

docs/changelog/next_release/186.feature.rst
syncmaster/schemas/v1/transfers/__init__.py
syncmaster/schemas/v1/transfers/transformations/dataframe_columns_filter.py
syncmaster/schemas/v1/transfers/transformations/dataframe_rows_filter.py
syncmaster/schemas/v1/transformation_types.py
syncmaster/worker/handlers/db/base.py
syncmaster/worker/handlers/db/clickhouse.py
syncmaster/worker/handlers/db/hive.py
syncmaster/worker/handlers/db/mssql.py
syncmaster/worker/handlers/db/mysql.py
syncmaster/worker/handlers/db/oracle.py
syncmaster/worker/handlers/db/postgres.py
syncmaster/worker/handlers/file/base.py
syncmaster/worker/handlers/file/s3.py
tests/test_integration/test_run_transfer/conftest.py
tests/test_integration/test_run_transfer/test_clickhouse.py
tests/test_integration/test_run_transfer/test_hive.py
tests/test_integration/test_run_transfer/test_mssql.py
tests/test_integration/test_run_transfer/test_mysql.py
tests/test_integration/test_run_transfer/test_oracle.py
tests/test_integration/test_run_transfer/test_s3.py
tests/test_unit/test_transfers/test_create_transfer.py
tests/test_unit/test_transfers/test_file_transfers/test_update_transfer.py

- Added a schema for `DataframeColumnsFilter` transformation:  
```json
{
"type": "dataframe_columns_filter",
"filters": [
{
"type": "include",
"field": "col1"
},
{
"type": "rename",
"field": "col2",
"to": "new_col2"
},
{
"type": "cast",
"field": "col3",
"as_type": "DATE"
}
]
}
```
- Supported filter types:
- `include`
- `rename`
- `cast`
- Implemented logic in the worker to handle DataframeColumnsFilter transformations: if a filter is present, it is applied to DBReader(columns=['"col1"', '"col2" AS "new_col2"', 'CAST("col3" as DATE) AS "col3"']) for DBHandler types and df.selectExpr("...") for FileHandlers. Filters are converted into a single SQL-like condition using AND, e.g.,
```SQL
"col1", "col2" AS "new_col2", CAST("col3" AS DATE) AS "col3"
```
(see …

[DOP-22350] Add transformations for Transfers with dataframe column filtering

---

syncmaster/settings/log/colored.yml
syncmaster/settings/log/json.yml
syncmaster/settings/log/plain.yml

Avoid worker logs from being flooded by p4j:
```
{"processName": "ForkPoolWorker-17", "process": 1964, "threadName": "Thread-9 (run)", "thread": 140076660934336, "name": "py4j.clientserver", "lineno": 575, "levelname": "INFO", "message": "Received command c on object id p1", "correlation_id": "-", "timestamp": "2025-01-28T12:27:19.166390+00:00"}
{"processName": "ForkPoolWorker-17", "process": 1964, "threadName": "Thread-9 (run)", "thread": 140076660934336, "name": "py4j.clientserver", "lineno": 575, "levelname": "INFO", "message": "Received command c on object id p1", "correlation_id": "-", "timestamp": "2025-01-28T12:27:19.169981+00:00"}
{"processName": "ForkPoolWorker-17", "process": 1964, "threadName": "Thread-9 (run)", "thread": 140076660934336, "name": "py4j.clientserver", "lineno": …
```

[DOP-23590] Change log level for py4j logs

---

docs/changelog/next_release/202.feature.rst
syncmaster/schemas/v1/connection_types.py
syncmaster/schemas/v1/transfers/__init__.py
syncmaster/schemas/v1/transfers/strategy.py
syncmaster/server/api/v1/connections.py
tests/test_unit/test_connections/test_read_connection_types.py
tests/test_unit/test_transfers/test_create_transfer.py
tests/test_unit/test_transfers/test_file_transfers/test_read_transfer.py
tests/test_unit/test_transfers/test_file_transfers/test_update_transfer.py
tests/test_unit/test_transfers/test_update_transfer.py

Added the `increment_by` field to the `IncrementalStrategy` schema. Implemented validation to ensure that for file based sources `increment_by` can only be `modified_since`, while for database sources it can be any string representing a column name.

[DOP-22126] Add incremental strategy to API

---

docs/changelog/next_release/211.feature.rst
syncmaster/worker/controller.py
syncmaster/worker/handlers/db/base.py
tests/test_integration/test_run_transfer/connection_fixtures/__init__.py
tests/test_integration/test_run_transfer/connection_fixtures/filters_fixtures.py
tests/test_integration/test_run_transfer/connection_fixtures/s3_fixtures.py
tests/test_integration/test_run_transfer/connection_fixtures/strategy_fixtures.py
tests/test_integration/test_run_transfer/test_clickhouse.py
tests/test_integration/test_run_transfer/test_ftp.py
tests/test_integration/test_run_transfer/test_ftps.py
tests/test_integration/test_run_transfer/test_hdfs.py
tests/test_integration/test_run_transfer/test_hive.py
tests/test_integration/test_run_transfer/test_mssql.py
tests/test_integration/test_run_transfer/test_mysql.py
tests/test_integration/test_run_transfer/test_oracle.py
tests/test_integration/test_run_transfer/test_s3.py
tests/test_integration/test_run_transfer/test_samba.py
tests/test_integration/test_run_transfer/test_sftp.py
tests/test_integration/test_run_transfer/test_webdav.py
tests/test_unit/test_auth/auth_fixtures/keycloak_fixture.py
tests/utils.py

- Implemented `DBReader` for incremental transfer with `AutoDetectHWM`, using a unique name composed of `transfer.id`, `transfer.source_connection.type`, and `transfer.source_params.table_name`
- Before writing data to the target, added a check in `HWMStore` for existing HWM. If absent or `strategy=full`, writer is initialized with `if_exists="replace_overlapping_partitions"` for Hive and `if_exists="replace_entire_table"` for other databases. Otherwise, `if_exists="append"` is used to prevent duplicates
- Developed integration tests to verify incremental reading, first fetching all source data, then a new subset.

[DOP-22132] Implement increment for transfers with DB source

---

docs/changelog/next_release/219.improvement.rst
syncmaster/dto/transfers.py
syncmaster/dto/transfers_resources.py
syncmaster/worker/controller.py
syncmaster/worker/handlers/db/base.py
syncmaster/worker/handlers/db/clickhouse.py
syncmaster/worker/handlers/db/hive.py
tests/test_integration/test_run_transfer/test_clickhouse.py

Enabled parallel reading for JDBC sources:  
- If `max_parallel_tasks == 1`, no changes to reading parameters  
- If `strategy.type == incremental` and HWM exists in `HWMStore`, used `increment_by` column with `partitioning_mode=range`. Efficient for indexed primary key with conditions
- If `strategy.type == incremental` and HWM does not exist, used `increment_by` column with `partitioning_mode=hash`. Full scan is more efficient than index lookup
- If `strategy.type == full`, retrieved the source schema, selected the first column, and used `partitioning_mode=hash`. Works regardless of column type and is efficient for full scans

[DOP-22297] Parallel reading from JDBC sources

---

docker/Dockerfile.worker
docs/changelog/0.2.2.rst
docs/changelog/index.rst
syncmaster/worker/handlers/file/hdfs.py
syncmaster/worker/spark.py

Now `HDFS` and `Hive` connection types call `kinit` before creating Spark session. `HDFS` connection uses KerberosClient instead of InsecureClient.

[DOP-25451] Fix Hive/HDFS connectors ignoring user & password
